SELECT dtc.OWNER,
	   dtc.TABLE_NAME,
		dtc.COLUMN_ID,
	   dtc.COLUMN_NAME,
	   dtc.DATA_TYPE,

	   dtc.DATA_LENGTH,
	   dtc.DATA_PRECISION,
	   dtc.DATA_SCALE,

	   dtc.NULLABLE,
	   
	   
	   dtc.CHARACTER_SET_NAME,
	   dtc.CHAR_COL_DECL_LENGTH,

	 
	   dtc.CHAR_LENGTH,
	   dtc.CHAR_USED,
	  
	   dtc.HIDDEN_COLUMN,
	   dtc.VIRTUAL_COLUMN,
	   dtc.SEGMENT_COLUMN_ID,
	   dtc.INTERNAL_COLUMN_ID,

	   dtc.QUALIFIED_COL_NAME,
	   dtc.USER_GENERATED,
	   dtc.DEFAULT_ON_NULL,
	   dtc.IDENTITY_COLUMN,
	   dtc.SENSITIVE_COLUMN,
	   dtc.EVALUATION_EDITION,
	   dtc.UNUSABLE_BEFORE,
	   dtc.UNUSABLE_BEGINNING,
	   dtc.COLLATION,
	   dtc.COLLATED_COLUMN_ID
FROM DBA_TAB_COLS dtc
WHERE OWNER IN (
	 SELECT username
	 FROM DBA_USERS au
	 WHERE au.ORACLE_MAINTAINED = 'N'
		AND username NOT IN ('APEXUSER', 'ORDS_PUBLIC_USER', 'ORDS_METADATA')
   )
  AND dtc.OWNER='ABEDINI'
  ORDER BY dtc.OWNER, dtc.TABLE_NAME,dtc.INTERNAL_COLUMN_ID